#calls the reusable workflow
name: Call the reusable workflow

on: [push]

jobs:
  call-workflow-passing-data:
    uses: leshemo/WpfApplicationBuild/.github/workflows/Reusable-BuildRelease-dotnetFramework.yml@main
    with:
      #name of the sln file to build. CHANGE TO project sln file name.
      slnName: xxx.sln
      #location of the files to be zipped and then released. DEFAULT is bin/Release to just release the artifacts created by the build process.
      filesToZipLocation: bin/Release
